const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
const User = require('./models/User');
const Product = require('./models/Product');
const Category = require('./models/Category');

dotenv.config();

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected');

    // Clear existing data
    await User.deleteMany();
    await Product.collection.drop();
    await Category.deleteMany();
    console.log('Cleared existing data');

    // Create admin user
    const adminPassword = await bcrypt.hash('admin123', 10);
    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@timeora.com',
      password: adminPassword,
      role: 'admin',
    });
    console.log('Admin user created');

    // Create categories
    const categories = await Category.create([
      { name: 'Automatic Watches', description: 'Self-winding luxury timepieces' },
      { name: 'Chronograph Watches', description: 'Precision timing watches' },
      { name: 'Men\'s Watches', description: 'Elegant watches for men' },
      { name: 'Women\'s Watches', description: 'Stylish watches for women' },
      { name: 'Smart Watches', description: 'Modern smart timepieces' },
      { name: 'Premium Watches', description: 'High-end luxury watches' },
    ]);
    console.log('Categories created');

    const categoryMap = {};
    categories.forEach(cat => {
      categoryMap[cat.name] = cat._id;
    });

    // Create demo products
    const products = [
      {
        name: 'Royal Chronograph Elite',
        slug: 'royal-chronograph-elite',
        brand: 'AUREL',
        description: 'A stunning chronograph watch with precision timing and elegant design. Features a stainless steel case, sapphire crystal, and genuine leather strap.',
        price: 45000,
        discountPrice: 38250,
        category: categoryMap['Automatic Watches'],
        images: ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400'],
        stock: 15,
        rating: 4.8,
        reviewCount: 42,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Genuine Leather',
          dialColor: 'Black',
          movement: 'Automatic',
          waterResistance: '100m',
          warranty: '2 Years',
          caseSize: '42mm',
        },
        featured: true,
        trending: true,
        bestseller: true,
        newArrival: true,
      },
      {
        name: 'Classic Heritage Automatic',
        slug: 'classic-heritage-automatic',
        brand: 'CHRONOVA',
        description: 'Timeless elegance meets modern craftsmanship. This automatic watch features a classic design with premium materials.',
        price: 35000,
        discountPrice: 31500,
        category: categoryMap['Automatic Watches'],
        images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400'],
        stock: 20,
        rating: 4.6,
        reviewCount: 35,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Stainless Steel',
          dialColor: 'Silver',
          movement: 'Automatic',
          waterResistance: '50m',
          warranty: '2 Years',
          caseSize: '40mm',
        },
        featured: true,
        bestseller: true,
      },
      {
        name: 'Sport Pro Chronograph',
        slug: 'sport-pro-chronograph',
        brand: 'VELORA',
        description: 'Built for the active lifestyle. This sport chronograph offers durability and precision timing.',
        price: 28000,
        category: categoryMap['Chronograph Watches'],
        images: ['https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=400'],
        stock: 25,
        rating: 4.5,
        reviewCount: 28,
        specifications: {
          caseMaterial: 'Titanium',
          strapMaterial: 'Rubber',
          dialColor: 'Blue',
          movement: 'Quartz',
          waterResistance: '200m',
          warranty: '2 Years',
          caseSize: '44mm',
        },
        trending: true,
        newArrival: true,
      },
      {
        name: 'Elegant Rose Gold',
        slug: 'elegant-rose-gold',
        brand: 'NEXUS',
        description: 'A luxurious rose gold timepiece perfect for special occasions. Features diamond accents and premium finish.',
        price: 65000,
        discountPrice: 58500,
        category: categoryMap['Women\'s Watches'],
        images: ['https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400'],
        stock: 10,
        rating: 4.9,
        reviewCount: 18,
        specifications: {
          caseMaterial: 'Rose Gold',
          strapMaterial: 'Genuine Leather',
          dialColor: 'Mother of Pearl',
          movement: 'Automatic',
          waterResistance: '30m',
          warranty: '3 Years',
          caseSize: '36mm',
        },
        featured: true,
        bestseller: true,
      },
      {
        name: 'Modern Smart Watch',
        slug: 'modern-smart-watch',
        brand: 'ORION',
        description: 'Stay connected with this premium smart watch featuring health tracking, notifications, and elegant design.',
        price: 22000,
        discountPrice: 19800,
        category: categoryMap['Smart Watches'],
        images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400'],
        stock: 30,
        rating: 4.4,
        reviewCount: 56,
        specifications: {
          caseMaterial: 'Aluminum',
          strapMaterial: 'Silicone',
          dialColor: 'AMOLED',
          movement: 'Smart',
          waterResistance: '50m',
          warranty: '1 Year',
          caseSize: '44mm',
        },
        trending: true,
        newArrival: true,
      },
      {
        name: 'Executive Black Edition',
        slug: 'executive-black-edition',
        brand: 'ELITE',
        description: 'A sophisticated black edition watch for the modern executive. Features premium materials and exceptional craftsmanship.',
        price: 52000,
        category: categoryMap['Premium Watches'],
        images: ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400'],
        stock: 12,
        rating: 4.7,
        reviewCount: 22,
        specifications: {
          caseMaterial: 'Black PVD Steel',
          strapMaterial: 'Black Leather',
          dialColor: 'Black',
          movement: 'Automatic',
          waterResistance: '100m',
          warranty: '3 Years',
          caseSize: '41mm',
        },
        featured: true,
        trending: true,
      },
      {
        name: 'Vintage Inspired Classic',
        slug: 'vintage-inspired-classic',
        brand: 'AUREL',
        description: 'A vintage-inspired classic with modern reliability. Perfect for those who appreciate traditional watchmaking.',
        price: 32000,
        discountPrice: 28800,
        category: categoryMap['Automatic Watches'],
        images: ['https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=400'],
        stock: 18,
        rating: 4.5,
        reviewCount: 31,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Brown Leather',
          dialColor: 'Cream',
          movement: 'Automatic',
          waterResistance: '50m',
          warranty: '2 Years',
          caseSize: '39mm',
        },
        bestseller: true,
      },
      {
        name: 'Diamond Accent Ladies',
        slug: 'diamond-accent-ladies',
        brand: 'CHRONOVA',
        description: 'Elegant ladies watch with diamond accents. A perfect blend of luxury and sophistication.',
        price: 48000,
        discountPrice: 43200,
        category: categoryMap['Women\'s Watches'],
        images: ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400'],
        stock: 8,
        rating: 4.8,
        reviewCount: 15,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Stainless Steel',
          dialColor: 'Silver',
          movement: 'Quartz',
          waterResistance: '30m',
          warranty: '2 Years',
          caseSize: '34mm',
        },
        featured: true,
        newArrival: true,
      },
      {
        name: 'Aviator Pilot Watch',
        slug: 'aviator-pilot-watch',
        brand: 'VELORA',
        description: 'Inspired by aviation heritage. This pilot watch features a large dial and precise timekeeping.',
        price: 38000,
        category: categoryMap['Chronograph Watches'],
        images: ['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=400'],
        stock: 14,
        rating: 4.6,
        reviewCount: 24,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Canvas',
          dialColor: 'Black',
          movement: 'Automatic',
          waterResistance: '100m',
          warranty: '2 Years',
          caseSize: '46mm',
        },
        trending: true,
      },
      {
        name: 'Minimalist Design Watch',
        slug: 'minimalist-design-watch',
        brand: 'NEXUS',
        description: 'Clean lines and minimalist design. Perfect for everyday wear with sophisticated simplicity.',
        price: 18000,
        discountPrice: 16200,
        category: categoryMap['Men\'s Watches'],
        images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400'],
        stock: 35,
        rating: 4.3,
        reviewCount: 45,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Mesh',
          dialColor: 'White',
          movement: 'Quartz',
          waterResistance: '50m',
          warranty: '2 Years',
          caseSize: '38mm',
        },
        bestseller: true,
        newArrival: true,
      },
      {
        name: 'Luxury Gold Edition',
        slug: 'luxury-gold-edition',
        brand: 'ORION',
        description: 'Pure luxury in gold. This premium gold edition watch exudes sophistication and elegance.',
        price: 85000,
        discountPrice: 76500,
        category: categoryMap['Premium Watches'],
        images: ['https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=400'],
        stock: 5,
        rating: 5.0,
        reviewCount: 12,
        specifications: {
          caseMaterial: '18K Gold',
          strapMaterial: 'Gold',
          dialColor: 'Gold',
          movement: 'Automatic',
          waterResistance: '30m',
          warranty: '5 Years',
          caseSize: '40mm',
        },
        featured: true,
        bestseller: true,
        trending: true,
      },
      {
        name: 'Diver Professional',
        slug: 'diver-professional',
        brand: 'ELITE',
        description: 'Professional diving watch with exceptional water resistance and luminous dial.',
        price: 42000,
        category: categoryMap['Chronograph Watches'],
        images: ['https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=400'],
        stock: 16,
        rating: 4.7,
        reviewCount: 19,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Rubber',
          dialColor: 'Black',
          movement: 'Automatic',
          waterResistance: '300m',
          warranty: '3 Years',
          caseSize: '44mm',
        },
        featured: true,
      },
      {
        name: 'Rose Gold Ladies Classic',
        slug: 'rose-gold-ladies-classic',
        brand: 'AUREL',
        description: 'A beautiful rose gold classic for ladies. Elegant and timeless design.',
        price: 29000,
        discountPrice: 26100,
        category: categoryMap['Women\'s Watches'],
        images: ['https://images.unsplash.com/photo-1618220179428-22790b461013?w=400'],
        stock: 22,
        rating: 4.5,
        reviewCount: 27,
        specifications: {
          caseMaterial: 'Rose Gold Plated',
          strapMaterial: 'Rose Gold Plated',
          dialColor: 'Silver',
          movement: 'Quartz',
          waterResistance: '30m',
          warranty: '2 Years',
          caseSize: '32mm',
        },
        trending: true,
        newArrival: true,
      },
      {
        name: 'Smart Fitness Pro',
        slug: 'smart-fitness-pro',
        brand: 'CHRONOVA',
        description: 'Advanced fitness tracking with smart features. The perfect companion for an active lifestyle.',
        price: 25000,
        category: categoryMap['Smart Watches'],
        images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400'],
        stock: 28,
        rating: 4.4,
        reviewCount: 38,
        specifications: {
          caseMaterial: 'Polycarbonate',
          strapMaterial: 'Silicone',
          dialColor: 'LCD',
          movement: 'Smart',
          waterResistance: '50m',
          warranty: '1 Year',
          caseSize: '42mm',
        },
        bestseller: true,
      },
      {
        name: 'Ceramic Luxury Watch',
        slug: 'ceramic-luxury-watch',
        brand: 'VELORA',
        description: 'Premium ceramic construction with scratch-resistant properties. Ultra-modern design.',
        price: 55000,
        discountPrice: 49500,
        category: categoryMap['Premium Watches'],
        images: ['https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=400'],
        stock: 9,
        rating: 4.8,
        reviewCount: 16,
        specifications: {
          caseMaterial: 'Ceramic',
          strapMaterial: 'Ceramic',
          dialColor: 'Black',
          movement: 'Automatic',
          waterResistance: '50m',
          warranty: '3 Years',
          caseSize: '43mm',
        },
        featured: true,
        trending: true,
      },
      {
        name: 'Moonphase Edition',
        slug: 'moonphase-edition',
        brand: 'NEXUS',
        description: 'Featuring a beautiful moonphase complication. A watch for true watch enthusiasts.',
        price: 72000,
        category: categoryMap['Automatic Watches'],
        images: ['https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=400'],
        stock: 7,
        rating: 4.9,
        reviewCount: 11,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Alligator Leather',
          dialColor: 'Blue',
          movement: 'Automatic',
          waterResistance: '50m',
          warranty: '3 Years',
          caseSize: '42mm',
        },
        featured: true,
        bestseller: true,
      },
      {
        name: 'Titanium Sport Watch',
        slug: 'titanium-sport-watch',
        brand: 'ORION',
        description: 'Lightweight titanium construction for comfort and durability. Perfect for sports enthusiasts.',
        price: 33000,
        discountPrice: 29700,
        category: categoryMap['Chronograph Watches'],
        images: ['https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=400'],
        stock: 20,
        rating: 4.6,
        reviewCount: 23,
        specifications: {
          caseMaterial: 'Titanium',
          strapMaterial: 'Titanium',
          dialColor: 'Grey',
          movement: 'Quartz',
          waterResistance: '200m',
          warranty: '2 Years',
          caseSize: '45mm',
        },
        trending: true,
        newArrival: true,
      },
      {
        name: 'Mother of Pearl Ladies',
        slug: 'mother-of-pearl-ladies',
        brand: 'ELITE',
        description: 'Elegant mother of pearl dial with beautiful iridescence. A true feminine masterpiece.',
        price: 39000,
        category: categoryMap['Women\'s Watches'],
        images: ['https://images.unsplash.com/photo-1585123334908-8a5b0e5b8d7c?w=400'],
        stock: 11,
        rating: 4.7,
        reviewCount: 14,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Stainless Steel',
          dialColor: 'Mother of Pearl',
          movement: 'Quartz',
          waterResistance: '30m',
          warranty: '2 Years',
          caseSize: '35mm',
        },
        featured: true,
      },
      {
        name: 'Skeleton Automatic',
        slug: 'skeleton-automatic',
        brand: 'AUREL',
        description: 'Transparent case back revealing the intricate automatic movement. Watchmaking artistry.',
        price: 48000,
        discountPrice: 43200,
        category: categoryMap['Automatic Watches'],
        images: ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400'],
        stock: 13,
        rating: 4.8,
        reviewCount: 20,
        specifications: {
          caseMaterial: 'Stainless Steel',
          strapMaterial: 'Brown Leather',
          dialColor: 'Skeleton',
          movement: 'Automatic',
          waterResistance: '50m',
          warranty: '3 Years',
          caseSize: '42mm',
        },
        featured: true,
        trending: true,
        bestseller: true,
      },
      {
        name: 'Limited Edition Platinum',
        slug: 'limited-edition-platinum',
        brand: 'CHRONOVA',
        description: 'Limited edition platinum watch. Only 100 pieces made. Ultimate luxury and exclusivity.',
        price: 150000,
        discountPrice: 135000,
        category: categoryMap['Premium Watches'],
        images: ['https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=400'],
        stock: 3,
        rating: 5.0,
        reviewCount: 5,
        specifications: {
          caseMaterial: 'Platinum',
          strapMaterial: 'Platinum',
          dialColor: 'Silver',
          movement: 'Manual',
          waterResistance: '30m',
          warranty: '5 Years',
          caseSize: '40mm',
        },
        featured: true,
        trending: true,
        newArrival: true,
      },
    ];

    await Product.insertMany(products);
    console.log('Products created');

    console.log('Seed data completed successfully!');
    console.log('\n=== Admin Login Details ===');
    console.log('Email: admin@timeora.com');
    console.log('Password: admin123');
    console.log('=========================\n');

    process.exit();
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedData();
